### PR TITLE
Improved geodesic interpolate

### PR DESCRIPTION
**Pull request by GabrielBram**
Method for producing NEB pathways using the geodesic interpolation method of Zhu et al. [1]. Adapted to ASE objects, and operates with periodic boundary conditions and FixedAtom constraints of ASE. Compared to initial CARMM implementation, the current branch improves many functionalities, including evaluation speed for the path length and gradients, and actually evaluates the correct gradient expressions during optimization.

    Example
    -------
```
    from ase.io import read
    from carmm.build.neb.geodesic import GeodesicInterpolator
    from ase.constraints import FixAtoms
    from ase.mep import NEB

    # Example below produces a pathway with 6 interpolating images
    initial = read("initial.xyz")
    final = read("final.xyz")

    # If constraints are desired, specify as normal
    constraints = Fixatoms([0, 1])
    initial.set_constraints(constraints)
    final.set_constraints(constraints)

    # Interpolate images by iteratively generating images between the midpoint
    # images along the pathway
    geodesic = GeodesicInterpolator(initial, final, path_len=8)
    geodesic.init_path()

    # Smooth the pathway by performing a sweeping algorithm which reduces the
    # overall geodesic length of the pathway
    geodesic.sweep_iterative(sweeperiter=20)

    # Define the NEB pathway as normal
    neb = NEB(geodesic.images)
```

### CODE REVIEW

**Comment by GabrielBram** [comment]
Indeed, all commits from [0fa25c6]-[e8452a0] are part of the old branch.

**Comment by GabrielBram** [comment]
Just following up - once the new tests go through, can I have an approval for this PR (@robinsonmt1 @kush2803)?

**Review by GaryLZW — APPROVED** [review]
This looks good to me.

**Review by kush2803 — APPROVED** [review]
Looks good.

**Pull request merged**
