### PR TITLE
Geodesic Interpolated Starting Path

### PR DESCRIPTION
**Pull request by GabrielBram**
Implements the initial path construction specified in: https://pubs.aip.org/aip/jcp/article/150/16/164103/198363/Geodesic-interpolation-for-reaction-pathways.

Code by and large lifted from the repository associated with the paper: https://github.com/virtualzx-nad/geodesic-interpolate/tree/master. However, this implementation honours FixAtoms constraints and periodic boundary conditions in ASE.

Essentially gives a more robust starting guess for the initial path than linear interpolation. Although the full geodesic interpolation algorithm is not implemented, the path should give a better starting guess for IDPP (IDPP uses the linear interpolation as a starting guess and suffers from nasty clashes if two atoms pass through one another).

Test case shows a 120 degree rotation of a CH3 group in ethane, which would otherwise fail spectacularly with the default IDPP interpolation without a better starting guess.

Best use for now would look like:      

```
from carmm.build.neb.geodesic import GeodesicInterpolator
from ase.mep import idpp_interpolate, NEB

Geodesic = GeodesicInterpolator(initial, final, 6, None)
Geodesic.init_path()

idpp_interpolate(Geodesic.images, mic=True)
mep = NEB(Geodesic.images)
...
```

### CODE REVIEW

**Comment by GabrielBram** [comment]
(A warning: This is all desperately uncommented)

**Comment by logsdail** [comment]
@GabrielBram Is this still needed? Or does #172 supersede this request, and it should be closed/merged?

**Comment by GabrielBram** [comment]
> @GabrielBram Is this still needed? Or does #172 supersede this request, and it should be closed/merged?

My mistake - I thought this was already merged. This branch is superseded by the more recently PR. Will close.

**Comment by GabrielBram** [comment]
Will clean the current branch once the newer one is merged.

**Pull request closed without merging**
