### PR TITLE
Update ARCHER2 species defaults

### PR DESCRIPTION
**Pull request by ikowalec**

### CODE REVIEW

**Comment by ikowalec** [comment]
>>>from carmm.run.aims_path import set_aims_command
>>>import os
>>>set_aims_command("archer2")
>>>os.system("echo $AIMS_SPECIES_DIR")

/work/e05/e05-files-log/shared/software/fhi-aims/species_defaults/defaults_2010/light

**Comment by logsdail** [comment]
I think this might be overworked - I'll try to add some comments that will simplify and remove some "if" statements.

**Comment by logsdail** [comment]
Additional request - please add comment under function definition as to what this variable is, and also update regression test so 2010/2020 are tested.

**Comment by ikowalec** [comment]
Lines 13-14 of the regression test will cover the new code (no changes necessary as if statements removed after last commit)

**Comment by ikowalec** [comment]
I tested locally and it gives the right path, so should be good to go

**Review by logsdail — APPROVED** [review]
All good

**Pull request merged**
