### PR TITLE
Update aims_calculator.py

### PR DESCRIPTION
**Pull request by logsdail**
Tried changing the compute_forces command to a Boolean.

### CODE REVIEW

**Comment by logsdail** [comment]
@robinsonmt1 tests pass so presume we are all good. Might be worth double-checking locally somewhere, or on Hawk?

**Comment by robinsonmt1** [comment]
Not sure if your change of compute_forces to _forces in the ase 3.23 section was on purpose, but I've tested both and compute_forces is the one that works

**Comment by logsdail** [comment]
[like]  Andrew Logsdail reacted to your message:
________________________________

**Comment by logsdail** [comment]
There is only so much we can test and we can't call the FHI-aims executable. So we can only test as you have here, which is appreciated.

**Comment by robinsonmt1** [comment]
I'm looking to see if there's any way to retrieve the arguments from a created Aims calculator object to see if we can test it like that, but I can't find anything at the moment other than setting the arguments

**Comment by robinsonmt1** [comment]
Right, I've found that you can output them using the getattr() inbuilt python function. I'll add this to the test to check the default settings go through

**Comment by logsdail** [comment]
[like]  Andrew Logsdail reacted to your message:
________________________________

**Comment by logsdail** [comment]
> @logsdail Can you do an informal review into my changes? (I don't think I can set you as a reviewer since this is your pull request)
> 
> Also not quite sure why the codecov has gone DOWN when I've ADDED tests... Edit: I've just spotted it's not testing the ASE 3.23 section. Is this something we want to change? To mess with the virtual environment on the fly?

The different versions of ASE are checked on different Python environments. The decrease in coverage was on the patch as there was a big if statement; by reducing the size of the fork, the coverage improved to passable. Thanks again!

**Pull request merged**
