### PR TITLE
Chemshell assign

### PR DESCRIPTION
**Pull request by OscarvanVuren**
Updates to the current state of the Chemshell implementations within carmm to provide a simple interface for the generation of QM/MM models with varying QM region shapes (spherical, unit cell, conventional cell) and sizes. Contains an amount of ASE dependency so if not appropriate for inclusion into Chemshell yet.

### CODE REVIEW

**Comment by logsdail** [comment]
Just glancing in, it looks like you've included 3 binary files in this branch that shouldn't be here?

**Comment by OscarvanVuren** [comment]
Not sure why they are included, I'll have a look later.

**Comment by OscarvanVuren** [comment]
These binary files are generated by Chemshell when the code is executed. They are produced by CPython when it is called in the workflow.

**Comment by logsdail** [comment]
Sure - but I don't think they should be in the repository?
________________________________

**Comment by OscarvanVuren** [comment]
Closing due to requirements for Chemshell; ultimately this code does not belong here and should only be pulled when it has no Chemshell dependencies.

**Pull request closed without merging**
